// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Receiver             int64    `protobuf:"varint,2,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func (m *Transaction) GetReceiver() int64 {
	if m != nil {
		return m.Receiver
	}
	return 0
}

func (m *Transaction) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Transaction) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ListTransaction struct {
	Transactions         []*Transaction       `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,3,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListTransaction) Reset()         { *m = ListTransaction{} }
func (m *ListTransaction) String() string { return proto.CompactTextString(m) }
func (*ListTransaction) ProtoMessage()    {}
func (*ListTransaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *ListTransaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTransaction.Unmarshal(m, b)
}
func (m *ListTransaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTransaction.Marshal(b, m, deterministic)
}
func (m *ListTransaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTransaction.Merge(m, src)
}
func (m *ListTransaction) XXX_Size() int {
	return xxx_messageInfo_ListTransaction.Size(m)
}
func (m *ListTransaction) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTransaction.DiscardUnknown(m)
}

var xxx_messageInfo_ListTransaction proto.InternalMessageInfo

func (m *ListTransaction) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func (m *ListTransaction) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *ListTransaction) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type TransactionRequest struct {
	TransactionId        int64    `protobuf:"varint,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionRequest) Reset()         { *m = TransactionRequest{} }
func (m *TransactionRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionRequest) ProtoMessage()    {}
func (*TransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *TransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionRequest.Unmarshal(m, b)
}
func (m *TransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionRequest.Marshal(b, m, deterministic)
}
func (m *TransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionRequest.Merge(m, src)
}
func (m *TransactionRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionRequest.Size(m)
}
func (m *TransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionRequest proto.InternalMessageInfo

func (m *TransactionRequest) GetTransactionId() int64 {
	if m != nil {
		return m.TransactionId
	}
	return 0
}

type ListTransactionRequest struct {
	TransactionId        []int64  `protobuf:"varint,1,rep,packed,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListTransactionRequest) Reset()         { *m = ListTransactionRequest{} }
func (m *ListTransactionRequest) String() string { return proto.CompactTextString(m) }
func (*ListTransactionRequest) ProtoMessage()    {}
func (*ListTransactionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *ListTransactionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListTransactionRequest.Unmarshal(m, b)
}
func (m *ListTransactionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListTransactionRequest.Marshal(b, m, deterministic)
}
func (m *ListTransactionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListTransactionRequest.Merge(m, src)
}
func (m *ListTransactionRequest) XXX_Size() int {
	return xxx_messageInfo_ListTransactionRequest.Size(m)
}
func (m *ListTransactionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListTransactionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListTransactionRequest proto.InternalMessageInfo

func (m *ListTransactionRequest) GetTransactionId() []int64 {
	if m != nil {
		return m.TransactionId
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "profile.proto.v2.Transaction")
	proto.RegisterType((*ListTransaction)(nil), "profile.proto.v2.ListTransaction")
	proto.RegisterType((*TransactionRequest)(nil), "profile.proto.v2.TransactionRequest")
	proto.RegisterType((*ListTransactionRequest)(nil), "profile.proto.v2.ListTransactionRequest")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0x1a, 0x2d, 0x76, 0xaa, 0xb6, 0x5d, 0xa4, 0x84, 0x68, 0x35, 0x06, 0x85, 0x9c, 0x52,
	0x88, 0x17, 0xa1, 0x07, 0xa9, 0xa2, 0x50, 0xe8, 0x29, 0x56, 0x10, 0x2f, 0xb2, 0x4d, 0xb6, 0x65,
	0xa1, 0x4d, 0x62, 0x76, 0x13, 0xf0, 0x6b, 0xfc, 0x1d, 0x3f, 0x4b, 0x9a, 0x4d, 0xdb, 0x6d, 0x2a,
	0xe9, 0x71, 0x66, 0xdf, 0x9b, 0x37, 0xef, 0x4d, 0x02, 0x6d, 0x1e, 0xe3, 0x80, 0x61, 0x8f, 0xd3,
	0x30, 0xb0, 0xa3, 0x38, 0xe4, 0x21, 0x6a, 0x45, 0x71, 0x38, 0xa5, 0x73, 0x22, 0x4a, 0x3b, 0x75,
	0xf4, 0xab, 0x59, 0x18, 0xce, 0xe6, 0xa4, 0x97, 0x35, 0x26, 0xc9, 0xb4, 0xc7, 0xe9, 0x82, 0x30,
	0x8e, 0x17, 0x91, 0xc0, 0xe8, 0xe7, 0x45, 0x00, 0x59, 0x44, 0xfc, 0x5b, 0x3c, 0x9a, 0x29, 0x34,
	0xc6, 0x1b, 0x11, 0xd4, 0x05, 0xc0, 0x9e, 0x17, 0x26, 0x01, 0xff, 0xa4, 0xbe, 0xa6, 0x18, 0x8a,
	0xa5, 0xba, 0xf5, 0xbc, 0x33, 0xf4, 0x91, 0x0e, 0x47, 0x31, 0xf1, 0x08, 0x4d, 0x49, 0xac, 0x55,
	0xb3, 0xc7, 0x75, 0x8d, 0xce, 0xe0, 0x30, 0xc5, 0xf3, 0x84, 0x68, 0xaa, 0xa1, 0x58, 0x8a, 0x2b,
	0x0a, 0xd4, 0x81, 0x1a, 0xe3, 0x98, 0x27, 0x4c, 0x3b, 0x30, 0x14, 0xab, 0xee, 0xe6, 0x95, 0xf9,
	0xab, 0x40, 0x73, 0x44, 0x19, 0x97, 0xc5, 0x07, 0x70, 0x2c, 0x19, 0x66, 0x9a, 0x62, 0xa8, 0x56,
	0xc3, 0xe9, 0xda, 0x45, 0xcb, 0xb6, 0x44, 0x72, 0xb7, 0x28, 0xe8, 0x1e, 0xea, 0x4f, 0x31, 0xc1,
	0x9c, 0xf8, 0x03, 0x9e, 0x6d, 0xd8, 0x70, 0x74, 0x5b, 0xf8, 0xb7, 0x57, 0xfe, 0xed, 0xf1, 0x2a,
	0x20, 0x77, 0x03, 0x5e, 0x32, 0xdf, 0x22, 0x3f, 0x67, 0xaa, 0xfb, 0x99, 0x6b, 0xb0, 0xd9, 0x07,
	0x24, 0x2f, 0x44, 0xbe, 0x12, 0xc2, 0x38, 0xba, 0x85, 0x53, 0x69, 0xb3, 0x4d, 0x9a, 0x27, 0x52,
	0x77, 0xe8, 0x9b, 0x0f, 0xd0, 0x29, 0xc4, 0x50, 0x36, 0x40, 0xdd, 0x19, 0xe0, 0xfc, 0x54, 0xb7,
	0xe4, 0x5f, 0x49, 0x9c, 0x52, 0x8f, 0xa0, 0x11, 0xb4, 0x85, 0xb7, 0xad, 0xeb, 0x96, 0x46, 0xa9,
	0x77, 0x76, 0xfc, 0x3e, 0x2f, 0xbf, 0x14, 0xb3, 0x82, 0xde, 0xa1, 0xf9, 0x42, 0x03, 0x5f, 0x9e,
	0x75, 0x53, 0x7e, 0x16, 0x61, 0x42, 0x2f, 0x57, 0x34, 0x2b, 0x08, 0x43, 0xab, 0xe0, 0x9f, 0x21,
	0x6b, 0x97, 0xf4, 0x7f, 0x46, 0xfa, 0xf5, 0x5e, 0xa4, 0x59, 0x79, 0xbc, 0xfc, 0xb8, 0xc8, 0x51,
	0xe2, 0x17, 0xe8, 0xa5, 0x4e, 0x5f, 0xca, 0x70, 0x52, 0xcb, 0xba, 0x77, 0x7f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x8f, 0xff, 0xd9, 0x26, 0x6e, 0x03, 0x00, 0x00,
}
